spring.application.name=coderunner
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/coderunner
spring.datasource.username=postgres
spring.datasource.password=Iamchinnu

spring.testcases.max_size=2.0
spring.testcases.base_path=/questions/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379