spring.application.name=coderunner-workers
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.data.redis.host=localhost
spring.data.redis.port=6379


spring.datasource.url=jdbc:postgresql://localhost:5432/coderunner
spring.datasource.username=postgres
spring.datasource.password=Iamchinnu




spring.stream.stream_name=submission-stream
spring.stream.consumer_name=consumer

spring.execution.maximum-thread-count=10